import { labelsRepo } from './custom'

export default {
  testnet: {
    DEFILLAMA_YIELDS_URL: 'https://yields.llama.fi/pools',
    BREVIS_API_URL: 'https://incentra-prd.brevis.network/sdk/v1/eulerCampaigns',
    BREVIS_MERKLE_PROOF_URL: 'https://incentra-prd.brevis.network/v1/getMerkleProofsBatch',
    EULER_INTERFACES_CHAINS_URL: 'https://raw.githubusercontent.com/euler-xyz/euler-interfaces/refs/heads/master/EulerChains.json',
    getEulerInterfacesTokenAddressesUrl: (chainId: number) => `https://raw.githubusercontent.com/euler-xyz/euler-interfaces/refs/heads/master/addresses/${chainId}/TokenAddresses.json`,
    getEulerLabelsEntitiesUrl: (chainId: number) => `https://raw.githubusercontent.com/euler-xyz/euler-labels/refs/heads/tac-turin/test/${chainId}/entities.json`,
    getEulerLabelsProductsUrl: (chainId: number) => `https://raw.githubusercontent.com/euler-xyz/euler-labels/refs/heads/tac-turin/test/${chainId}/products.json`,
    getEulerLabelsEarnVaultsUrl: (chainId: number) => `https://raw.githubusercontent.com/euler-xyz/euler-labels/refs/heads/tac-turin/test/${chainId}/earn-vaults.json`,
    getEulerLabelsPointsUrl: (chainId: number) => `https://raw.githubusercontent.com/euler-xyz/euler-labels/refs/heads/tac-turin/test/${chainId}/points.json`,
    EULER_LABELS_LOGO_URL: `https://raw.githubusercontent.com/${labelsRepo}/refs/heads/master/logo`,
    MERKL_API_BASE_URL: 'https://api.merkl.xyz/v4',
  },
  mainnet: {
    DEFILLAMA_YIELDS_URL: 'https://yields.llama.fi/pools',
    BREVIS_API_URL: 'https://incentra-prd.brevis.network/sdk/v1/eulerCampaigns',
    BREVIS_MERKLE_PROOF_URL: 'https://incentra-prd.brevis.network/v1/getMerkleProofsBatch',
    EULER_INTERFACES_CHAINS_URL: 'https://raw.githubusercontent.com/euler-xyz/euler-interfaces/refs/heads/master/EulerChains.json',
    getEulerInterfacesTokenAddressesUrl: (chainId: number) => `https://raw.githubusercontent.com/euler-xyz/euler-interfaces/refs/heads/master/addresses/${chainId}/TokenAddresses.json`,
    SUBGRAPH_URI_1: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-mainnet/latest/gn',
    SUBGRAPH_URI_56: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-bsc/latest/gn',
    SUBGRAPH_URI_130: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-unichain/latest/gn',
    SUBGRAPH_URI_146: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-sonic/latest/gn',
    SUBGRAPH_URI_239: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-tac/latest/gn',
    SUBGRAPH_URI_1923: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-swell/latest/gn',
    SUBGRAPH_URI_8453: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-base/latest/gn',
    SUBGRAPH_URI_9745: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-plasma/latest/gn',
    SUBGRAPH_URI_42161: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-arbitrum/latest/gn',
    SUBGRAPH_URI_43114: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-avalanche/latest/gn',
    SUBGRAPH_URI_59144: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-linea/latest/gn',
    SUBGRAPH_URI_60808: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-bob/latest/gn',
    SUBGRAPH_URI_80094: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-berachain/latest/gn',
    SUBGRAPH_URI_143: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-simple-monad/latest/gn',
    //SUBGRAPH_HYPEREVM_URI: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-v2-hyperevm/latest/gn',
    //SUBGRAPH_INK_URI: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-v2-ink/latest/gn',
    //SUBGRAPH_MANTLE_URI: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-v2-mantle/latest/gn',
    //SUBGRAPH_PLASMA_OPTIMISM: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-v2-optimism/latest/gn',
    //SUBGRAPH_PLASMA_WORLDCHAIN: 'https://api.goldsky.com/api/public/project_cm4iagnemt1wp01xn4gh1agft/subgraphs/euler-v2-worldchain/latest/gn',
    MERKL_ADDRESS_1: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    MERKL_ADDRESS_56: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    MERKL_ADDRESS_130: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    MERKL_ADDRESS_146: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    MERKL_ADDRESS_239: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    MERKL_ADDRESS_1923: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    MERKL_ADDRESS_8453: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    MERKL_ADDRESS_9745: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    MERKL_ADDRESS_42161: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    MERKL_ADDRESS_43114: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    MERKL_ADDRESS_59144: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    MERKL_ADDRESS_60808: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    MERKL_ADDRESS_80094: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    MERKL_ADDRESS_143: '0x3Ef3D8bA38EBe18DB133cEc108f4D14CE00Dd9Ae',
    getEulerLabelsEntitiesUrl: (chainId: number) => `https://raw.githubusercontent.com/${labelsRepo}/refs/heads/master/${chainId}/entities.json`,
    getEulerLabelsProductsUrl: (chainId: number) => `https://raw.githubusercontent.com/${labelsRepo}/refs/heads/master/${chainId}/products.json`,
    getEulerLabelsEarnVaultsUrl: (chainId: number) => `https://raw.githubusercontent.com/${labelsRepo}/refs/heads/master/${chainId}/earn-vaults.json`,
    getEulerLabelsPointsUrl: (chainId: number) => `https://raw.githubusercontent.com/${labelsRepo}/refs/heads/master/${chainId}/points.json`,
    EULER_LABELS_LOGO_URL: `https://raw.githubusercontent.com/${labelsRepo}/refs/heads/master/logo`,
    MERKL_API_BASE_URL: 'https://api.merkl.xyz/v4',
  },
}
